# Generated by Django 3.0b1 on 2020-02-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hash',
            field=models.TextField(null=True),
        ),
    ]
