# Generated by Django 3.0b1 on 2020-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
