# Generated by Django 3.0b1 on 2020-02-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(default='0', editable=False),
        ),
    ]
